---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: plexcloudmusic/vpn-status

inputs:
  - name: status-trigger
  - name: vpn-status-repo

run:
  path: vpn-status-repo/tasks/post-state/task.sh
